//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from tdx.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="tdxParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
public interface ItdxVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="tdxParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] tdxParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>line_fun</c>
	/// labeled alternative in <see cref="tdxParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_fun([NotNull] tdxParser.Line_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>none_fun</c>
	/// labeled alternative in <see cref="tdxParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNone_fun([NotNull] tdxParser.None_funContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tdxParser.attach"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttach([NotNull] tdxParser.AttachContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tdxParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColor([NotNull] tdxParser.ColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tdxParser.draw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDraw([NotNull] tdxParser.DrawContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MEMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMEMA_fun([NotNull] tdxParser.MEMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RANGE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRANGE_fun([NotNull] tdxParser.RANGE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COVAR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOVAR_fun([NotNull] tdxParser.COVAR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FINDLOWBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFINDLOWBARS_fun([NotNull] tdxParser.FINDLOWBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CEILING_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCEILING_fun([NotNull] tdxParser.CEILING_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWMA_fun([NotNull] tdxParser.WMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REFV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREFV_fun([NotNull] tdxParser.REFV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub_fun([NotNull] tdxParser.AddSub_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROC_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROC_fun([NotNull] tdxParser.ROC_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FILTERX_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFILTERX_fun([NotNull] tdxParser.FILTERX_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOWRANGE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOWRANGE_fun([NotNull] tdxParser.LOWRANGE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVR_fun([NotNull] tdxParser.VR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TROUGHBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTROUGHBARS_fun([NotNull] tdxParser.TROUGHBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RELATE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRELATE_fun([NotNull] tdxParser.RELATE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BARSSINCEN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBARSSINCEN_fun([NotNull] tdxParser.BARSSINCEN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXV_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXV_REF_fun([NotNull] tdxParser.INDEXV_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTMA_fun([NotNull] tdxParser.TMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MIN_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMIN_EXT_fun([NotNull] tdxParser.MIN_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VALUEWHEN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVALUEWHEN_fun([NotNull] tdxParser.VALUEWHEN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EVERY_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEVERY_fun([NotNull] tdxParser.EVERY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MASS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMASS_fun([NotNull] tdxParser.MASS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HOD_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHOD_fun([NotNull] tdxParser.HOD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Judge_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJudge_fun([NotNull] tdxParser.Judge_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DEVSQ_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDEVSQ_fun([NotNull] tdxParser.DEVSQ_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PARAMETER_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPARAMETER_REF_fun([NotNull] tdxParser.PARAMETER_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MAX_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMAX_fun([NotNull] tdxParser.MAX_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TAN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTAN_fun([NotNull] tdxParser.TAN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ZIG_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZIG_fun([NotNull] tdxParser.ZIG_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STDDEV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTDDEV_fun([NotNull] tdxParser.STDDEV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ZIGA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZIGA_fun([NotNull] tdxParser.ZIGA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NOT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNOT_fun([NotNull] tdxParser.NOT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EMV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEMV_fun([NotNull] tdxParser.EMV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREF_fun([NotNull] tdxParser.REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTR_fun([NotNull] tdxParser.TR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TROUGH_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTROUGH_fun([NotNull] tdxParser.TROUGH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXO_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXO_REF_fun([NotNull] tdxParser.INDEXO_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWR_fun([NotNull] tdxParser.WR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>POW_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPOW_fun([NotNull] tdxParser.POW_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LWINNER_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLWINNER_fun([NotNull] tdxParser.LWINNER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MTM_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMTM_fun([NotNull] tdxParser.MTM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BARSLAST_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBARSLAST_fun([NotNull] tdxParser.BARSLAST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MINUTE_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMINUTE_REF_fun([NotNull] tdxParser.MINUTE_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOW_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOW_REF_fun([NotNull] tdxParser.LOW_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MAX6_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMAX6_fun([NotNull] tdxParser.MAX6_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAMA_fun([NotNull] tdxParser.AMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UPNDAY_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUPNDAY_fun([NotNull] tdxParser.UPNDAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FILTER_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFILTER_fun([NotNull] tdxParser.FILTER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TRIX_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTRIX_fun([NotNull] tdxParser.TRIX_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PEAKBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPEAKBARS_fun([NotNull] tdxParser.PEAKBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FINDLOW_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFINDLOW_fun([NotNull] tdxParser.FINDLOW_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SLOPE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSLOPE_fun([NotNull] tdxParser.SLOPE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MULAR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMULAR_fun([NotNull] tdxParser.MULAR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MOD_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMOD_fun([NotNull] tdxParser.MOD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TURN_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTURN_REF_fun([NotNull] tdxParser.TURN_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TIME_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTIME_REF_fun([NotNull] tdxParser.TIME_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LLV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLLV_fun([NotNull] tdxParser.LLV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COST_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOST_fun([NotNull] tdxParser.COST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BBI_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBBI_fun([NotNull] tdxParser.BBI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOS_fun([NotNull] tdxParser.COS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLN_fun([NotNull] tdxParser.LN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PPART_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPPART_fun([NotNull] tdxParser.PPART_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMA_fun([NotNull] tdxParser.MA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUM_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUM_fun([NotNull] tdxParser.SUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOD_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOD_fun([NotNull] tdxParser.LOD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOD_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOD_EXT_fun([NotNull] tdxParser.LOD_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SQRT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSQRT_fun([NotNull] tdxParser.SQRT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MFI_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMFI_fun([NotNull] tdxParser.MFI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CONST_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCONST_fun([NotNull] tdxParser.CONST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DRAWNULL_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDRAWNULL_fun([NotNull] tdxParser.DRAWNULL_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ATAN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATAN_fun([NotNull] tdxParser.ATAN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RSI_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRSI_fun([NotNull] tdxParser.RSI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXC_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXC_REF_fun([NotNull] tdxParser.INDEXC_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MONTH_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMONTH_REF_fun([NotNull] tdxParser.MONTH_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IFN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIFN_fun([NotNull] tdxParser.IFN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DOWNNDAY_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDOWNNDAY_fun([NotNull] tdxParser.DOWNNDAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FINDHIGH_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFINDHIGH_fun([NotNull] tdxParser.FINDHIGH_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WEEKDAY_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWEEKDAY_REF_fun([NotNull] tdxParser.WEEKDAY_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LLVBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLLVBARS_fun([NotNull] tdxParser.LLVBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DTPRICE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDTPRICE_fun([NotNull] tdxParser.DTPRICE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HHV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHHV_fun([NotNull] tdxParser.HHV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COUNT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOUNT_fun([NotNull] tdxParser.COUNT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FINDHIGHBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFINDHIGHBARS_fun([NotNull] tdxParser.FINDHIGHBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BACKSET_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBACKSET_fun([NotNull] tdxParser.BACKSET_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CROSS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCROSS_fun([NotNull] tdxParser.CROSS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>REVERSE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitREVERSE_fun([NotNull] tdxParser.REVERSE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bracket_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_fun([NotNull] tdxParser.Bracket_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ZTPRICE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZTPRICE_fun([NotNull] tdxParser.ZTPRICE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INTPART_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINTPART_fun([NotNull] tdxParser.INTPART_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BARSLASTCOUNT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBARSLASTCOUNT_fun([NotNull] tdxParser.BARSLASTCOUNT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LLV_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLLV_EXT_fun([NotNull] tdxParser.LLV_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUM_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUM_EXT_fun([NotNull] tdxParser.SUM_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HOD_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHOD_EXT_fun([NotNull] tdxParser.HOD_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STD_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTD_fun([NotNull] tdxParser.STD_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BIAS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBIAS_fun([NotNull] tdxParser.BIAS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MIN6_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMIN6_fun([NotNull] tdxParser.MIN6_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATETODAY_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATETODAY_fun([NotNull] tdxParser.DATETODAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AVEDEV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAVEDEV_fun([NotNull] tdxParser.AVEDEV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>COSTEX_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCOSTEX_fun([NotNull] tdxParser.COSTEX_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EXISTR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEXISTR_fun([NotNull] tdxParser.EXISTR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BETWEEN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBETWEEN_fun([NotNull] tdxParser.BETWEEN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSMA_fun([NotNull] tdxParser.SMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AMOUNT_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAMOUNT_REF_fun([NotNull] tdxParser.AMOUNT_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DPO_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDPO_fun([NotNull] tdxParser.DPO_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DAY_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDAY_REF_fun([NotNull] tdxParser.DAY_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HOUR_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHOUR_REF_fun([NotNull] tdxParser.HOUR_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ISVALID_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitISVALID_fun([NotNull] tdxParser.ISVALID_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VAR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVAR_fun([NotNull] tdxParser.VAR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SIGN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSIGN_fun([NotNull] tdxParser.SIGN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FLOOR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFLOOR_fun([NotNull] tdxParser.FLOOR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OBV_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOBV_fun([NotNull] tdxParser.OBV_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MIN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMIN_fun([NotNull] tdxParser.MIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PEAK_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPEAK_fun([NotNull] tdxParser.PEAK_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CLOSE_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCLOSE_REF_fun([NotNull] tdxParser.CLOSE_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ACOS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitACOS_fun([NotNull] tdxParser.ACOS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OPEN_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOPEN_REF_fun([NotNull] tdxParser.OPEN_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>YEAR_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYEAR_REF_fun([NotNull] tdxParser.YEAR_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NUM_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNUM_fun([NotNull] tdxParser.NUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOG_NUM_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOG_NUM_fun([NotNull] tdxParser.LOG_NUM_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ABS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitABS_fun([NotNull] tdxParser.ABS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROUND2_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROUND2_fun([NotNull] tdxParser.ROUND2_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DATE_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDATE_REF_fun([NotNull] tdxParser.DATE_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ATR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATR_fun([NotNull] tdxParser.ATR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SAR_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSAR_fun([NotNull] tdxParser.SAR_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VOL_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVOL_REF_fun([NotNull] tdxParser.VOL_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIF_fun([NotNull] tdxParser.IF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STDP_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTDP_fun([NotNull] tdxParser.STDP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HIGH_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHIGH_REF_fun([NotNull] tdxParser.HIGH_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ASIN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitASIN_fun([NotNull] tdxParser.ASIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MAX_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMAX_EXT_fun([NotNull] tdxParser.MAX_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FRACPART_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFRACPART_fun([NotNull] tdxParser.FRACPART_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PSY_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPSY_fun([NotNull] tdxParser.PSY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDiv_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDiv_fun([NotNull] tdxParser.MulDiv_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HHV_EXT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHHV_EXT_fun([NotNull] tdxParser.HHV_EXT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TIME2_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTIME2_REF_fun([NotNull] tdxParser.TIME2_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDMA_fun([NotNull] tdxParser.DMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SIN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSIN_fun([NotNull] tdxParser.SIN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WINNER_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWINNER_fun([NotNull] tdxParser.WINNER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BARSSINCE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBARSSINCE_fun([NotNull] tdxParser.BARSSINCE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FORCAST_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFORCAST_fun([NotNull] tdxParser.FORCAST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOG_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOG_fun([NotNull] tdxParser.LOG_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXH_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXH_REF_fun([NotNull] tdxParser.INDEXH_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BARSCOUNT_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBARSCOUNT_fun([NotNull] tdxParser.BARSCOUNT_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LONGCROSS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLONGCROSS_fun([NotNull] tdxParser.LONGCROSS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ASI_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitASI_fun([NotNull] tdxParser.ASI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SUMBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSUMBARS_fun([NotNull] tdxParser.SUMBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TOPRANGE_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTOPRANGE_fun([NotNull] tdxParser.TOPRANGE_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AndOr_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndOr_fun([NotNull] tdxParser.AndOr_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EMA_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEMA_fun([NotNull] tdxParser.EMA_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TR_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTR_REF_fun([NotNull] tdxParser.TR_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DAYSTOTODAY_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDAYSTOTODAY_REF_fun([NotNull] tdxParser.DAYSTOTODAY_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LAST_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLAST_fun([NotNull] tdxParser.LAST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXL_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXL_REF_fun([NotNull] tdxParser.INDEXL_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PWINNER_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPWINNER_fun([NotNull] tdxParser.PWINNER_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CCI_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCCI_fun([NotNull] tdxParser.CCI_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NDAY_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNDAY_fun([NotNull] tdxParser.NDAY_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EXP_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEXP_fun([NotNull] tdxParser.EXP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ROUND_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitROUND_fun([NotNull] tdxParser.ROUND_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SARTURN_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSARTURN_fun([NotNull] tdxParser.SARTURN_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VARP_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVARP_fun([NotNull] tdxParser.VARP_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INDEXA_REF_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINDEXA_REF_fun([NotNull] tdxParser.INDEXA_REF_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HHVBARS_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHHVBARS_fun([NotNull] tdxParser.HHVBARS_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EXIST_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEXIST_fun([NotNull] tdxParser.EXIST_funContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PARAMETER_fun</c>
	/// labeled alternative in <see cref="tdxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPARAMETER_fun([NotNull] tdxParser.PARAMETER_funContext context);
}
